#pragma once

#define GPULDA_POIS_MAX_LAMBDA 100
#define GPULDA_POIS_MAX_VALUE 200
#define GPULDA_COMPUTE_D_IDX_BLOCKDIM 256
#define GPULDA_POLYA_URN_COLSUMS_BLOCKDIM 128
#define GPULDA_POLYA_URN_SAMPLE_BLOCKDIM 256
#define GPULDA_SAMPLE_TOPICS_BLOCKDIM 256
#define GPULDA_SAMPLE_TOPICS_GRIDDIM 32
