#pragma once

#define GPLDA_POIS_MAX_LAMBDA 100
#define GPLDA_POIS_MAX_VALUE 200
#define GPLDA_COMPUTE_D_IDX_BLOCKDIM 256
#define GPLDA_POLYA_URN_COLSUMS_BLOCKDIM 128
#define GPLDA_POLYA_URN_SAMPLE_BLOCKDIM 256
#define GPLDA_WARP_SAMPLE_TOPICS_BLOCKDIM 32
#define GPLDA_HASH_STASH_SIZE 101
#define GPLDA_HASH_NUM_FUNCTIONS 4
